version: '3.8'

services:
  backend:
    build: ./mushroom-identification-backend
    ports:
      - "8080:8080"
    env_file:
      - ./mushroom-identification-backend/.env
    restart: unless-stopped
