spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
spring.jpa.properties.jpa.entity.listener.allow-cdi-injection=true

spring.docker.compose.enabled=false
spring.profiles.active=prod

app.cors.allowed-origins=https://fleinsoppkontroll.no
