name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  pages: write        # for GitHub Pages deployment
  id-token: write     # for OIDC token if needed

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build and Stage Site
        run: |
          # Generate Maven site with JaCoCo report into target/site
          mvn clean verify site site:stage -Pcoverage
          # Generate Javadoc into the staged site
          mvn javadoc:javadoc site:stage

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: target/staging

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
